import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="w_adm_navi_wrap">
        <Link href="/wdm/slist" className="w_lk">상품목록</Link> | 
        <Link href="/wdm/swrite" className="w_lk">상품등록</Link> | 
        <Link href="/wdm/optlist" className="w_lk">옵션목록</Link> | 
        <Link href="/wdm/optwrite" className="w_lk">옵션등록</Link> | 
        <Link href="/wdm/rsvlist" className="w_lk">예약현황</Link> | 
        <Link href="/wdm/swritemm" className="w_lk">멀티테스트</Link> 
      </div>

      {children}
    </>
  );
}
