import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w_adm_body_wrap">
      <div className="w_adm_navi_wrap">
        <Link href="/wdm/slist" className="btn btn-primary">여행상품 관리</Link>&nbsp; 
        <Link href="/wdm/optlist" className="btn btn-primary">여행옵션션 관리</Link>&nbsp;
        <Link href="/wdm/rsvlist" className="btn btn-primary">예약현황</Link>&nbsp;
        <Link href="/" className="btn btn-primary">사용자홈</Link> 
      </div>
      
      <div className="w_adm_lay_wrap">
        <div className="w_adm_lay_sub_wrap">{children}</div>
        
      </div>
      
    </div>
  );
}
